Updated RPM build to latest version

diff --git a/packaging/el/sd-agent-pkg.init b/packaging/el/sd-agent-pkg.init
--- a/packaging/el/sd-agent-pkg.init
+++ b/packaging/el/sd-agent-pkg.init
@@ -15,10 +15,10 @@
 
 ### BEGIN INIT INFO
 # Provides: sd-agent
-# Short-Description: Start and start sd-agent
+# Short-Description: Start and stop sd-agent
 # Description: sd-agent is the monitoring agent component for Server Density
-# Required-Start:
-# Required-Stop:
+# Required-Start: $remote_fs
+# Required-Stop: $remote_fs
 # Default-Start: 2 3 4 5
 # Default-Stop: 0 1 6
 ### END INIT INFO
@@ -26,6 +26,10 @@
 # Source function library.
 if [ -f /etc/init.d/functions ]; then
         . /etc/init.d/functions
+fi
+
+if [ -f /lib/lsb/init-functions ]; then
+        . /lib/lsb/init-functions
 fi
 
 if [ -f /etc/SuSE-release ]; then
@@ -46,7 +50,11 @@ SUPERVISOR_FILE="/etc/sd-agent/supervisor.conf"
 SUPERVISOR_SOCK="/var/tmp/sd-supervisor.sock"
 SUPERVISORCTL_PATH="/usr/share/python/sd-agent/bin/supervisorctl"
 SUPERVISORD_PATH="/usr/share/python/sd-agent/bin/supervisord"
+COLLECTOR_PIDFILE="/var/run/sd-agent/sd-agent.pid"
 SYSTEM_PATH=/usr/share/python/sd-agent/bin:$PATH
+
+# Captures processes in the supervisord group that are 'optional' i.e. not essential for the agent to run
+SD_OPT_PROC_REGEX="sdstatsd|jmxfetch"
 
 if [ ! -x $AGENTPATH ]; then
     echo "$AGENTPATH not found. Exiting."
@@ -54,6 +62,18 @@ if [ ! -x $AGENTPATH ]; then
 fi
 
 check_status() {
+
+    QUERY="all"
+    if [ -n "$1" ] && [ "$1" != "all" ] && [ "$1" != "essential" ] && [ "$1" != "optional" ]; then
+        echo "Valid arguments for $0: all | essential | optional"
+    elif [ -n "$1" ]; then
+        QUERY=$1
+    fi
+
+    ESSENTIAL=0
+    OPTIONAL=0
+    FAIL=1
+
     # If the socket exists, we can use supervisorctl
     if [ -e $SUPERVISOR_SOCK ]; then
         # If we're using supervisor, check the number of sd processes
@@ -61,17 +81,45 @@ check_status() {
         # same as the number of programs specified in the supervisor config
         # file:
 
-        supervisor_processes=$(PATH=$SYSTEM_PATH $SUPERVISORCTL_PATH -c $SUPERVISOR_FILE status)
+        supervisor_processes=$($SUPERVISORCTL_PATH -c $SUPERVISOR_FILE status)
 
-        # Number of RUNNING supervisord programs
+        # Number of RUNNING supervisord programs (ignoring optional procs captured by $SD_OPT_PROC_REGEX)
         sd_supervisor_processes=$(echo "$supervisor_processes" |
+                                       grep -Ev $SD_OPT_PROC_REGEX |
                                        grep $NAME |
                                        grep -c RUNNING)
 
-        # Number of expected running supervisord programs
-        supervisor_config_programs=$(grep -c '\[program:' $SUPERVISOR_FILE)
+        # Number of non-failed OPTIONAL supervisord programs
+        sd_supervisor_opt_processes=$(echo "$supervisor_processes" |
+                                      grep -E $SD_OPT_PROC_REGEX |
+                                      grep $NAME |
+                                      grep -cv FATAL)
+
+        # Number of expected running supervisord programs (ignoring optional procs)
+        supervisor_config_programs=$(grep -Ev $SD_OPT_PROC_REGEX $SUPERVISOR_FILE |
+                                     grep -c '\[program:')
+
+        # Number of expected optional supervisord programs
+        supervisor_config_opt_programs=$(grep -E $SD_OPT_PROC_REGEX $SUPERVISOR_FILE |
+                                         grep -c '\[program:')
 
         if [ "$sd_supervisor_processes" -ne "$supervisor_config_programs" ]; then
+            ESSENTIAL=1
+        fi
+
+        if [ "$sd_supervisor_opt_processes" -ne "$supervisor_config_opt_programs" ]  ; then
+            OPTIONAL=1
+        fi
+
+        if [ "$QUERY" = "essential" ] && [ "$ESSENTIAL" -eq 0 ]; then
+            FAIL=0
+        elif [ "$QUERY" = "optional" ] && [ "$OPTIONAL" -eq 0 ]; then
+            FAIL=0
+        elif [ "$QUERY" = "all" ] && [ "$ESSENTIAL" = "$OPTIONAL" ] && [ $ESSENTIAL -eq 0 ]; then
+            FAIL=0
+        fi
+
+        if [ "$FAIL" -gt 0 ]; then
             echo "$supervisor_processes"
             echo "$DESC (supervisor) is NOT running all child processes"
             return 1
@@ -79,6 +127,7 @@ check_status() {
             echo "$DESC (supervisor) is running all child processes"
             return 0
         fi
+
     else
         echo "$DESC (supervisor) is not running"
         return 1
@@ -88,6 +137,7 @@ check_status() {
 # Action to take
 case "$1" in
     start)
+
         # Could be removed during boot
         test -e /var/run/sd-agent || install -m 755 -o sd-agent -g sd-agent -d /var/run/sd-agent
 
@@ -96,7 +146,7 @@ case "$1" in
             exit 3
         fi
 
-        check_status > /dev/null
+        check_status essential > /dev/null
         if [ $? -eq 0 ]; then
             echo "$DESC is already running"
             exit 0
@@ -118,9 +168,8 @@ case "$1" in
         # check if the agent is running once per second for 10 seconds
         retries=10
         while [ $retries -gt 1 ]; do
-          if check_status > /dev/null; then
+          if check_status essential > /dev/null; then
               # We've started up successfully. Exit cleanly
-              exit 0
               exit 0
           else
               retries=$(($retries - 1))
@@ -146,13 +195,37 @@ case "$1" in
               # (right now only sd-agent supports additional flags)
         su $AGENTUSER -c "$AGENTPATH info $@"
         COLLECTOR_RETURN=$?
+        su $AGENTUSER -c "$SDSTATSDPATH info"
+        SDSTATSD_RETURN=$?
         su $AGENTUSER -c "$FORWARDERPATH info"
         FORWARDER_RETURN=$?
-        exit $(($COLLECTOR_RETURN+$FORWARDER_RETURN))
+        exit $(($COLLECTOR_RETURN+$SDSTATSD_RETURN+$FORWARDER_RETURN))
         ;;
 
     status)
-        check_status
+        # Note: sh does not support arrays
+        # Check for kernel version 3.18+ - overlayfs has known bug affecting unix domain sockets
+        major=$(echo "$( uname -r )" | cut -d"." -f1)
+        minor=$(echo "$( uname -r )" | cut -d"." -f2)
+        # If major version 3, and minor version 18+, OR major version 4+
+        if [ "$DOCKER_DD_AGENT" != "" ] && ( ( [ $major -eq 3 ] && [ $minor -ge 18 ] ) || [ $major -gt 3 ] ); then
+            RED='\033[0;31m' # Red Text
+            NC='\033[0m' # No Color
+            echo "${RED}Warning: Known bug in Linux Kernel 3.18+ causes 'status' to fail.${NC}"
+            echo "Calling 'info', instead..."
+            service sd-agent info
+            if [ $? -ne 0 ]; then
+                exit 1
+            fi
+        else
+            check_status
+        fi
+        exit $?
+        ;;
+
+    reload)
+        kill -HUP `cat $COLLECTOR_PIDFILE`
+        exit $?
         ;;
 
     restart|force-reload)
@@ -169,10 +242,15 @@ case "$1" in
         su $AGENTUSER -c "$AGENTPATH configcheck"
         exit $?
         ;;
+    jmx)
+        shift
+        su $AGENTUSER -c "$AGENTPATH jmx $@"
+        exit $?
+        ;;
 
     *)
         N=/etc/init.d/$NAME
-        echo "Usage: $N {start|stop|restart|info|status|configcheck|configtest}"
+        echo "Usage: $N {start|stop|restart|info|status|reload|configcheck|configtest|jmx}"
         exit 1
         ;;
 esac
