Applied merge fixes and branding improvements

diff --git a/debian/sd-agent.init b/debian/sd-agent.init
--- a/debian/sd-agent.init
+++ b/debian/sd-agent.init
@@ -15,7 +15,7 @@ PATH=$PATH:/sbin # add the location of start-stop-daemon on Debian
 
 AGENTPATH="/usr/share/python/sd-agent/agent.py"
 AGENTCONF="/etc/sd-agent/config.cfg"
-DOGSTATSDPATH="/usr/share/python/sd-agent/dogstatsd.py"
+SDSTATSDPATH="/usr/share/python/sd-agent/sdstatsd.py"
 AGENTUSER="sd-agent"
 FORWARDERPATH="/usr/share/python/sd-agent/sdagent.py"
 NAME="sd-agent"
@@ -27,7 +27,9 @@ SUPERVISORCTL_PATH="/usr/share/python/sd-agent/bin/supervisorctl"
 SUPERVISORD_PATH="/usr/share/python/sd-agent/bin/supervisord"
 COLLECTOR_PIDFILE="/var/run/sd-agent/sd-agent.pid"
 SYSTEM_PATH=/usr/share/python/sd-agent/bin:$PATH
-SD_OPT_PROC_REGEX="dogstatsd|jmxfetch|go-metro"
+
+# Captures processes in the supervisord group that are 'optional' i.e. not essential for the agent to run
+SD_OPT_PROC_REGEX="sdstatsd|jmxfetch"
 
 if [ ! -x $AGENTPATH ]; then
     echo "$AGENTPATH not found. Exiting."
@@ -54,25 +56,25 @@ check_status() {
         # same as the number of programs specified in the supervisor config
         # file:
 
-        supervisor_processes=$(PATH=$SYSTEM_PATH $SUPERVISORCTL_PATH -c $SUPERVISOR_FILE status)
+        supervisor_processes=$($SUPERVISORCTL_PATH -c $SUPERVISOR_FILE status)
 
-        # Number of RUNNING supervisord programs (ignoring dogstatsd, jmxfetch and go-metro)
+        # Number of RUNNING supervisord programs (ignoring optional procs captured by $SD_OPT_PROC_REGEX)
         sd_supervisor_processes=$(echo "$supervisor_processes" |
                                   grep -Ev $SD_OPT_PROC_REGEX |
                                   grep $NAME |
                                   grep -c RUNNING)
 
-        # Number of non-failed OPTIONAL supervisord programs (dogstatsd, jmxfetch and go-metro)
+        # Number of non-failed OPTIONAL supervisord programs
         sd_supervisor_opt_processes=$(echo "$supervisor_processes" |
                                       grep -E $SD_OPT_PROC_REGEX |
                                       grep $NAME |
                                       grep -cv FATAL)
 
-        # Number of expected running supervisord programs (ignoring dogstatsd, jmxfetch and go-metro)
+        # Number of expected running supervisord programs (ignoring optional procs)
         supervisor_config_programs=$(grep -Ev $SD_OPT_PROC_REGEX $SUPERVISOR_FILE |
                                      grep -c '\[program:')
 
-        # Number of expected optional supervisord programs (dogstatsd, jmxfetch and go-metro)
+        # Number of expected optional supervisord programs
         supervisor_config_opt_programs=$(grep -E $SD_OPT_PROC_REGEX $SUPERVISOR_FILE |
                                          grep -c '\[program:')
 
@@ -174,11 +176,11 @@ case "$1" in
               # (right now only sd-agent supports additional flags)
         su $AGENTUSER -c "$AGENTPATH info $@"
         COLLECTOR_RETURN=$?
+        su $AGENTUSER -c "$SDSTATSDPATH info"
+        SDSTATSD_RETURN=$?
         su $AGENTUSER -c "$FORWARDERPATH info"
         FORWARDER_RETURN=$?
-        su $AGENTUSER -c "$TRACEAGENTPATH -info"
-        TRACEAGENT_RETURN=$? # not used for now, Trace/APM not a core feature yet
-        exit $(($COLLECTOR_RETURN+$DOGSTATSD_RETURN+$FORWARDER_RETURN))
+        exit $(($COLLECTOR_RETURN+$SDSTATSD_RETURN+$FORWARDER_RETURN))
         ;;
 
     status)
@@ -222,9 +224,15 @@ case "$1" in
         exit $?
         ;;
 
+    jmx)
+        shift
+        su $AGENTUSER -c "$AGENTPATH jmx $@"
+        exit $?
+        ;;
+
     *)
         N=/etc/init.d/$NAME
-        echo "Usage: $N {start|stop|restart|info|status|reload|configcheck|configtest}"
+        echo "Usage: $N {start|stop|restart|info|status|reload|configcheck|configtest|jmx}"
         exit 1
         ;;
 esac
